name: diary
description: Diary app project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.4.3+7

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  table_calendar: 3.1.1
  lottie: 2.7.0
  intl: ^0.19.0
  hive_flutter: 1.1.0
  path_provider: ^2.1.1
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  animate_do: 3.1.2
  flutter_slidable: ^3.0.0
  toastification: ^2.0.0
  image_picker: ^1.0.4
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.2.1
  image: ^4.1.3
  salomon_bottom_bar: ^3.3.2
  flutter_masonry_view: 0.0.2
  flutter_svg: ^2.0.10+1
  iconly: ^1.0.1
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/lottie/
    - assets/png/
    - assets/png/empty_area/

  fonts:
    - family: outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
        - asset: assets/fonts/outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/outfit/Outfit-Black.ttf
          weight: 900
