name: diary
description: Diary app project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.4.2+6

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  table_calendar: 3.0.9
  ionicons: 0.2.2
  lottie: 2.7.0
  intl: ^0.18.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  sizer: 2.0.15
  animate_do: 3.1.2
  flutter_slidable: ^3.0.0
  image_picker: ^1.0.4
  flutter_colorpicker: 1.0.3
  url_launcher: ^6.2.1
  image: ^4.1.3
  flutter_masonry_view: 0.0.2



dev_dependencies: 
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/json/onboarding_screen_animation/onboarding_lottie_light.json
    - assets/json/onboarding_screen_animation/onboarding_lottie_dark.json
    - assets/images/forever_memories_logo/forever_memories_logo_white.png
    - assets/images/forever_memories_logo/forever_memories_logo_black.png
    - assets/images/fab/start_writing.png
    - assets/images/user_profile/user_profile.png
    - assets/images/empty_area/search_not_found_2.png
    - assets/images/empty_area/entry_not_found.png
    - assets/images/empty_area/photo_not_found.png
    - assets/images/empty_area/savedlist_not_found.png.png
    - assets/images/empty_area/archived_not_found.png

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 200
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 500
    
    - family: SFPRO
      fonts:
        - asset: assets/fonts/sfpro/SFPRODISPLAYREGULAR.otf
          weight: 300
        - asset: assets/fonts/sfpro/SFPRODISPLAYMEDIUM.otf
          weight: 400
        - asset: assets/fonts/sfpro/SFPRODISPLAYBOLD.otf
          weight: 500

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 500
