name: diary
description: Diary app project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.4.3+7

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  table_calendar: 3.0.9
  lottie: 2.7.0
  intl: ^0.18.1
  hive_flutter: 1.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  sizer: 2.0.15
  animate_do: 3.1.2
  flutter_slidable: ^3.0.0
  image_picker: ^1.0.4
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.2.1
  image: ^4.1.3
  flutter_masonry_view: 0.0.2
  flutter_svg: ^2.0.10+1
  iconly: ^1.0.1


dev_dependencies: 
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/lottie/
    - assets/png/
    - assets/png/empty_area/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Sathoshi/Satoshi-Medium.ttf
          weight: 500
    
    - family: SFPRO
      fonts:
        - asset: assets/fonts/SF Pro/SFPRODISPLAYREGULAR.otf
          weight: 400
        - asset: assets/fonts/SF Pro/SFPRODISPLAYMEDIUM.otf
          weight: 500
        - asset: assets/fonts/SF Pro/SFPRODISPLAYBOLD.otf
          weight: 600
