// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkyLihKZcq7XkJqe0YLH22r4QZg50DtRk',
    appId: '1:796656620929:web:97f5b5e4d7f8e2dd848480',
    messagingSenderId: '796656620929',
    projectId: 'diary-36ef3',
    authDomain: 'diary-36ef3.firebaseapp.com',
    storageBucket: 'diary-36ef3.appspot.com',
    measurementId: 'G-MX6L3Y0CPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0mJ54KcCz1SMA-RjeNOT7RBgiLZ9ca8',
    appId: '1:796656620929:android:35ed0a821be5688d848480',
    messagingSenderId: '796656620929',
    projectId: 'diary-36ef3',
    storageBucket: 'diary-36ef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_3QK0FJzcDXi71fgbowcbZ-D5ldDByyU',
    appId: '1:796656620929:ios:5532e8e3851c8a58848480',
    messagingSenderId: '796656620929',
    projectId: 'diary-36ef3',
    storageBucket: 'diary-36ef3.appspot.com',
    iosBundleId: 'com.example.diary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_3QK0FJzcDXi71fgbowcbZ-D5ldDByyU',
    appId: '1:796656620929:ios:276371b0f6d79f95848480',
    messagingSenderId: '796656620929',
    projectId: 'diary-36ef3',
    storageBucket: 'diary-36ef3.appspot.com',
    iosBundleId: 'com.example.diary.RunnerTests',
  );
}
